### ISSUE TITLE
Błąd logowania do forum

### ISSUE THREAD

**Issue by magul** [kodujdlapolski/KodujDlaPolski#1]
Podczas działającej sesji użytkownika na http://forum.kodujdlapolski.pl wyczyściłem pamięć przeglądarki - przez to utraciłem sesję (co jest oczywiste).

Niestety od tamtego czasu gdy próbuję się zalogować, to po podaniu hasła dostaję w popupie `{"error":"invalid_client","error_description":"Client id does not exist"}`. Zamykam popup i cały czas w głównym oknie nie jestem zalogowany. Jednocześnie na http://mojepanstwo.pl sesja się tworzy.

Przy następnej próbie zalogowania się do forum (gdy nie wyloguję sesji z moje państwo) w popupie dostaję od razu `{"error":"invalid_client","error_description":"Client id does not exist"}`

**Comment by KrzysztofMadejski** [comment]
https://mojepanstwo.pl/oauth/authorize?client_id=NTI1N2RhYjgzNDg1YTBk&redirect_uri=http%3A%2F%2Fforum.kodujdlapolski.pl%2Fauth%2Fepanstwo%2Fcallback&response_type=code&state=bee8d0c436bdfbcf4df806
zwraca ten błąd. Sprawdziłem ustawienia na forum i zaktualizowałem client_secret, ale nie pomogło. Client_id po stronie mojego państwa jest zdefiniowany w tabeli `clients`, więc dziwne, że go nie widzi.

@danielmacyszyn ?

**Comment by KrzysztofMadejski** [comment]
Poprawione i to na dobrze (miejmy nadzieję)!

**Comment by magul** [comment]
potwierdzam, działa!
