### ISSUE TITLE
Potwierdzić Coworkingness na najbliższy termin

### ISSUE THREAD

**Issue by magul** [kodujdlapolski/KodujDlaPolski#15]
Potwierdzić dostępność Coworkingness na czwartki, 18:30-21 zaczynając od 11 sierpnia.

**Comment by WojtekSanko** [comment]
W ten czwartek (11.08) nie jest jeszcze możliwe. Mają zaplanowaną imprezę. Negocjuję od następnego.

**Comment by WojtekSanko** [comment]
W ten czwartek (11.08) idziemy nam na imprezę i dogadujemy zasady i szczegóły. Wpadajcie. [http://coworkingness.com/pl/](url)

**Comment by magul** [comment]
Rozmawialiśmy z @WojtekSanko na fejsbuku z Oskarem (właściciel Coworkingness) i ustaliliśmy, że ruszamy z hacknightami od 25 sierpnia u nich. Temat do zamknięcia.
