### ISSUE TITLE
Wysyłanie maili ze skrzynki poznan@kodujdlapolski.pl

### ISSUE THREAD

**Issue by magul** [kodujdlapolski/KodujDlaPolski#31]
Mamy w planach wysłać email do programistów, którzy przy różnych okazjach zostawili nam swoje emaile. Chcielibyśmy zrobić to jako brygada i ze skrzynki brygadowej. Wiem, że mogę wysłać ze swojej imiennej, ale czy da się stworzyć (zamiast aliasu) skrzynkę poznan@kodujdlapolski.pl ?

Jeżeli problemem jest ta skrzynka, to czy można ten adres po prostu podpiąć pod moje konto imienne?

**Comment by KrzysztofMadejski** [comment]
Tak jak pisałem Wojtkowi w ustawieniach gmail spróbujcie dodać ten adres jako "Dodaj inny adres e-mail którego jesteś właścicielem". Powinno chwycić

**Comment by magul** [comment]
Zadziałało. Issue zamykam.
