### ISSUE TITLE
Hackathon nocny w Poznaniu

### ISSUE THREAD

**Issue by magul** [kodujdlapolski/KodujDlaPolski#34]
Dostałem coś takiego na fejsbuku:

```
Cześć! Pisałem jakiś czas temu na poznan@kodujdlapolski.pl, ale bez odpowiedzi, dlatego sprobuję na FB :). Organizuję 15 października Meetnight - nocną konferencję IT. 
Czy Koduj dla Polski byłoby zainteresowane współorganizowaniem hackathonu? Zależy nam przede wszystkim na kwestiach merytorycznych. 

My możemy zorganizować przestrzeń, która odpowiada Waszym wymaganiom oraz pomóc przy promocji.
Pozdrawiam serdecznie,
JR

Podsyłam link do wydarzenia: https://www.facebook.com/events/1555942671381188/
```

**Comment by magul** [comment]
[meetnight0316_informacja.pdf](https://github.com/kodujdlapolski/KodujDlaPolski/files/436855/meetnight0316_informacja.pdf)

**Comment by w1stler** [comment]
Przejrzę dzisiaj tę informację, ale inicjatywa raczej w porządku - będziemy się mogli nieco rozpromować. ;)

**Comment by magul** [comment]
No musimy jeszcze się zastanowić jak to zrobić, żeby miało to dla nas jak największy sens.

**Comment by ghost** [comment]
Tak przedyskutowaliśmy to z Magulem i bardziej opcja networkingowa dla nas - aniżeli organizowanie hackatonu/hacknightu, ponieważ nie sądzę, by przeznaczyli na to dużo czasu i chcą, byśmy się w to zaangażowali merytorycznie.
Choć może jakaś porywająca prezentacja?
