### ISSUE TITLE
Poszukać nowego miejsca na spotkania warszawskie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [kodujdlapolski/KodujDlaPolski#39]
Pomysły:
- [ ] Polidea?

**Comment by WojtekSanko** [comment]
- [ ] m65przestrzenkreatywna - https://www.facebook.com/m65przestrzenkreatywna/
- [ ] https://www.facebook.com/babkadowynajecia
- [ ] http://hardgamma.com/gammarebels/
- [ ] http://firma.um.warszawa.pl/projekty/centrum-kreatywnosci-targowa-56/
  Zgłoszę się dziś do nich wszystkich.

**Comment by KrzysztofMadejski** [comment]
Gamma rebels chyba nie istnieje już. Kiedyś z nimi rozmawiałem i chcieli kasę. Mało jest miejsc za friko w Warszawie.

**Comment by WojtekSanko** [comment]
Zostaliśmy w TechSoup. Miejsce spełnia wymogi i podoba się społeczności.
